In [1]:
import math

In [2]:
math.pi

3.141592653589793

In [3]:
math.e

2.718281828459045

In [4]:
math.inf

inf

In [5]:
math.ceil(7.8)

8

In [6]:
math.floor(7.8)

7

# NumPy 
Works with Multi-dimensional Array

In [7]:
import numpy as np

In [8]:
some_list = [1,2,3,4,5,6,7]
type(some_list)

list

In [9]:
some_array = np.array(some_list)
type(some_array)

numpy.ndarray

In [11]:
some_array #1D Array or vector

array([1, 2, 3, 4, 5, 6, 7])

In [12]:
ones_array = np.ones(5)
ones_array

array([1., 1., 1., 1., 1.])

In [13]:
range_array = np.arange(8)
range_array

array([0, 1, 2, 3, 4, 5, 6, 7])

In [14]:
reshaped_array = range_array.reshape(2,4)#Reshape- 2 rows and 4 columns
reshaped_array

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [15]:
random_array = np.random.random((4,5)) #Random Array
random_array

array([[0.12484219, 0.16176063, 0.67764983, 0.67278776, 0.89142134],
       [0.92727807, 0.18133231, 0.05358268, 0.13507261, 0.59213912],
       [0.34225903, 0.32967469, 0.06350754, 0.84406098, 0.66662224],
       [0.17629899, 0.13958486, 0.43835121, 0.58256805, 0.90552791]])

In [16]:
mean = np.mean(range_array) #Mean
mean

3.5

In [17]:
median = np.median(range_array) #Median
median

3.5

In [18]:
var = np.var(range_array)#Variance
var

5.25

In [19]:
std = np.std(range_array)#Standard Deviation
std

2.29128784747792

# Pandas
CSV - rows and columns 

dataframe - Its an object that has rows and columns and is used to hold data in the form of tables

In [20]:
import pandas as pd

In [21]:
df = pd.DataFrame({
    'name':['John','Alice','Bob','Eileen','Rob'],
    'gender':['Male','Female','Male','Female','Male'],
    'age':[45,20,30,14,67]
})

In [22]:
df

name  gender  age
0    John    Male   45
1   Alice  Female   20
2     Bob    Male   30
3  Eileen  Female   14
4     Rob    Male   67

**describe** - It gives quick statistical overview of all of the numeric columns that exist in your data.

In [24]:
df.describe()

age
count   5.000000
mean   35.200000
std    21.300235
min    14.000000
25%    20.000000
50%    30.000000
75%    45.000000
max    67.000000

In [25]:
 subset_df = df[['name','age']]#Subset of dataframes
subset_df

name  age
0    John   45
1   Alice   20
2     Bob   30
3  Eileen   14
4     Rob   67

In [26]:
groupby_df = df.groupby(by='gender').count()
groupby_df.head()

name  age
gender           
Female     2    2
Male       3    3